### ISSUE TITLE
Can you give more explanation about install process.

### ISSUE THREAD

**Issue by Inobiddinov** [c-bertran/codeshell#10]
I have a hard time understanding the installation part. It would be nice if you could give clear instructions for newbies like me. I tried to download both files but didn't manage to run the examshell.

**Comment by c-bertran** [comment]
Hi
Thank you for this issue. What is the problem with the installation process?
Normally you just have to get the last version corresponding to your system (https://github.com/c-bertran/42-exam-shell/releases/tag/0.3.7), then simply launch it via a Shell with the following command ./[executable name]

What point did you find obscure so that I could improve the readme ?
